apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: umjotebwr-nodejs
  janus-idp.io/tekton: umjotebwr-nodejs
  backstage.io/kubernetes-id: umjotebwr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: umjotebwr-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
